# Generated by Django 3.2.15 on 2022-09-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comute', '0002_about_aboutheader_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
